### ISSUE TITLE
Top5Reach

### ISSUE THREAD

**Issue by P1514** [P1514/Diversity#200]
Search is still done by pss on opinions table, perhaps should be changed to accounts and sources on models with that pss. Lets try evaluating the ammount of effort required.

**Comment by fcrsilva** [comment]
As I see this issue, we should take into account all the opinions on all pss's which are in a model, even when a certain pair source account is not contemplated in any model when obtaining the top reach pss's, in order to show the users info on the most popular pss's that they are concerned about. The query that is used for this is:

Select pss from opinions where pss in (Select distinct pss from models where archived=0) group by pss order by AVG(reach) desc limit 

What are your thoughts on this ?

**Comment by P1514** [comment]
Well each model only has one pss, so it should be all the opinions on all the models that corresponde to a specific pss. Column PSS on opinions table isn't reliable since the SN Filtering flop. Pairs Source Accounts that have no connection with PSS should not be considered since PSS column isn't reliable anymore. 

Should be something more aligned with:

1) Select uri,pss from models;
2) Process and find all pairs source accounts for each pss;
3) Get AVG(reach) for each PSS.
4) Filter Top 5
5) Calculate sentiment for those top5

**Comment by fcrsilva** [comment]
That makes sense, I'm going to fix that.

**Comment by fcrsilva** [comment]
Fixed
